packages/simulator/lib/address.js, packages/simulator/lib/car.js, packages/simulator/lib/distributors/pink_company.js, packages/simulator/lib/distributors/red_company.js, packages/simulator/lib/extractPoints.js, packages/simulator/lib/osrm.js, packages/simulator/lib/pool.js, packages/simulator/lib/streams/bookings.js, packages/simulator/lib/streams/postombud.js, packages/simulator/package-lock.json, packages/simulator/package.json, packages/simulator/run.js
Features:
- Car calculates its events and returns them as a stream when handle bookings is called
- Car can handle multiple bookings
- "Pools":
- A company has a pool that emits available cars whenever that company wants to emit them
- Cars put themselves back onto the pool after dropping off their last packages (can add pauses or whatever here)
- The actual simulator uses the pool stream to get available cars
- Simulator can handle multiple pools (companies), though it just hands off to whichever pool emits a car first
=> feat: simulator in rxjs

packages/simulator/__tests__/unit/dispatch.js, packages/simulator/index.js, packages/simulator/lib/car.js, packages/simulator/lib/pelias.js, packages/simulator/simulator/bookings.js, packages/simulator/simulator/cars.js, packages/simulator/simulator/dispatchCentral.js, packages/simulator/streams/population.js, packages/simulator/web/routes.js, packages/visualisation/src/App.js, packages/visualisation/src/Map.js
This fixes the bugs with cars not appearing due to too much cpu being spent on finding points in polygons. Also fixes the failing test.
=> Different way to load isCommercial (via pelias)

packages/simulator/index.js, packages/simulator/simulator/bookings.js, packages/simulator/simulator/dispatchCentral.js
Sample run:
Summary: 
- Is there a cache?
- Yes: Use it
- No:
- Generate bookings
- Write them to cache
=> feat: ephemeral cache for kommun bookings

packages/simulator/__tests__/unit/car.js, packages/simulator/__tests__/unit/cars.js, packages/simulator/__tests__/unit/dispatch.js, packages/simulator/index.js, packages/simulator/lib/booking.js, packages/simulator/lib/car.js, packages/simulator/lib/virtualTime.js, packages/simulator/web/routes.js, packages/visualisation/src/App.js, packages/visualisation/src/Map.js, packages/visualisation/src/components/Button/index.js, packages/visualisation/src/components/PlaybackOptions/index.js, packages/visualisation/src/icons/pause.svg, packages/visualisation/src/icons/play.svg
Button is functional in frontend. Sending socket to backend (play/pause) defending on state
Todo: implement in backend
=> feat: add button play/pause

README.md
Small spelling and wording updates — **Ready for review**
=> Format Readme to be more legible

packages/visualisation/src/App.js, packages/visualisation/src/components/Button/index.js, packages/visualisation/src/components/Typography/index.js, packages/visualisation/src/components/WelcomeBox/index.js
Welcome box first time you visit digital twin. When you click "okej" a cookie is set for 30 days.
=> Feat: welcome box

packages/visualisation/src/Map.js, packages/visualisation/src/components/TimeProgressBar/index.js
=> feat: only show hours and minutes 

packages/visualisation/src/Map.js
=> feat: hover info for busLineLayer

k8s/base/kibana.yaml, k8s/base/simulator.yaml, k8s/base/visualisation.yaml, k8s/dependencies/kustomization.yaml, k8s/dependencies/osrm.yaml, k8s/dependencies/vroom.yaml, packages/simulator/lib/osrm.js, skaffold.yaml
This PR uses the new cluster. Whenever we have tested it and verified all functionality we can move the DNS here.
=> feat: use the new cluster

packages/simulator/streams/kommuner.js
=> feat: include all 14 Norrbotten municipalities in visualization

packages/simulator/index.js, packages/simulator/lib/models/passenger.js, packages/simulator/lib/taxiDispatch.js, packages/simulator/lib/vehicles/taxi.js, packages/simulator/lib/virtualTime.js, packages/simulator/simulator/passengers.js, packages/simulator/web/routes.js, packages/visualisation/src/App.js, packages/visualisation/src/Map.js, packages/visualisation/src/components/HoverInfoBox/index.js
=> feat: let passengers have more than one journey planned in a day

k8s/base/simulator.yaml, packages/simulator/Dockerfile, packages/simulator/lib/elastic.js
Enable stage and production environments to talk to elasticsearch instances in stage and production
=> Connect simulator to elasticsearch

k8s/dependencies/kibana/elasticsearch.yaml, k8s/dependencies/kibana/kibana.yaml, k8s/overlays/prod/kibana.yaml
=> chore: add correct namespace and basic auth for kibana

packages/visualisation/src/components/ExperimentSection/index.js
This PR is a part of https://trello.com/c/KOuKWIWE/48-visualisera-resultat-av-experiment-i-kibana but does not resolve the whole ticket.
=> feat: link to experiment in kibana

packages/simulator/package-lock.json, packages/simulator/package.json
This ensures the projects runs without requiring a globally installed nodemon.
=> chore: depend on nodemon

packages/simulator/lib/dispatch/taxiDispatch.js, packages/simulator/lib/log.js, packages/simulator/lib/models/citizen.js, packages/simulator/lib/region.js, packages/simulator/lib/vehicles/bus.js, packages/simulator/lib/vehicles/taxi.js, packages/simulator/lib/vehicles/vehicle.js, packages/simulator/lib/vroom.js
To solve a problem where taxis would go back and forth for each passenger - it was easier to just send the bookings queue to vroom and then follow the instructions.
=> Use Vroom in taxis

k8s/dependencies/pelias/csv-importer.yaml
Use correct mountpath for csv-importer
=> chore: correct path for mount

packages/simulator/streams/publicTransport.js, packages/visualisation/package-lock.json
Intention is to make more clear that when the gtfs data is out of date, the software will tell you so:
=> chore: simulator will error if GTFS-data does not have service current day

README.md, k8s/base/digital-twin/simulator.yaml, k8s/overlays/digital-twin/simulator.yaml, k8s/overlays/helsingborg/simulator.yaml, k8s/overlays/rorla/simulator.yaml, packages/simulator/streams/gtfs.js
Mitigate unnecessary restrictions in Trafiklab's API...
=> chore: trafiklab

k8s/overlays/helsingborg/kustomization.yaml, k8s/overlays/rorla/kustomization.yaml, packages/simulator/web/routes.js, packages/visualisation/src/App.jsx, packages/visualisation/src/Map.jsx
Support setting initial map state so that the map shows the running experiment directly.
=> feat: map init state
